apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://webhook_user:webhook_pass@postgres-service:5432/webhook_db"
  POSTGRES_USER: "webhook_user"
  POSTGRES_PASSWORD: "webhook_pass"
  POSTGRES_DB: "webhook_db"