apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
data:
  REDIS_HOST: {{ .Values.config.redisHost }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  RATE_LIMIT: {{ .Values.config.rateLimit | quote }}