apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres-service:5432/{{ .Values.postgres.db }}"
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.db }}