input {
  udp {
    port => 5000
    codec => json {
      ecs_compatibility => disabled
    }
  }
}

filter {
  if [service] == "api" {
    mutate {
      add_field => { "[@metadata][index]" => "nexus-api" }
    }
  } else if [service] == "worker" {
    mutate {
      add_field => { "[@metadata][index]" => "nexus-worker" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "nexus-logs" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
    ecs_compatibility => disabled
  }
  stdout { codec => rubydebug }
}
